<?xml version="1.0"?>
<robot name="crrl_ugv" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
	     iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
             izz="${m*r*r/2}"
	     />
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
	      iyy="${m*(x*x+z*z)/12}" iyz = "0"
	      izz="${m*(x*x+z*z)/12}"
	      />
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
	      iyy="${2*m*r*r/5}" iyz = "0"
	      izz="${2*m*r*r/5}"
	      />
  </xacro:macro>

  <!-- NOTE: Wheel collision width is reduced to improve turning. Visually accurate -->
  <xacro:macro name="wheel" params="lr tY pos gap">

    <link name="${lr}_wheel">
      <collision>
	<origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
	<geometry>
	  <cylinder length="${wheel_width*0.01}" radius="${wheel_radius}"/>
	</geometry>
      </collision>

      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>

      <visual>
	<origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
	<geometry>
	  <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
	</geometry>
	<material name="black"/>
      </visual>

      <inertial>
	<origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
	<mass value="${wheel_mass}"/>
	<cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
      </inertial>
    </link>

    <gazebo reference="${lr}_wheel">
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${lr}_wheel_hinge" type="continuous">
      <parent link="base_link"/>
      <child link="${lr}_wheel"/>
      <origin xyz="${pos} ${tY*wheel_width/2+tY*chassis_width/2+gap} ${wheel_radius}" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="1.0" friction="1.0"/>
    </joint>

    <transmission name="${lr}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_wheel_hinge">
	<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}Motor">
	<hardwareInterface>EffortJointInterface</hardwareInterface>
	<mechanicalReduction>10</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
</robot>


