// Generated by gencpp from file sim_real_msg_interface/Commands.msg
// DO NOT EDIT!


#ifndef SIM_REAL_MSG_INTERFACE_MESSAGE_COMMANDS_H
#define SIM_REAL_MSG_INTERFACE_MESSAGE_COMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sim_real_msg_interface
{
template <class ContainerAllocator>
struct Commands_
{
  typedef Commands_<ContainerAllocator> Type;

  Commands_()
    : header()
    , velocity(0.0)
    , omega(0.0)  {
    }
  Commands_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity(0.0)
    , omega(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _omega_type;
  _omega_type omega;





  typedef boost::shared_ptr< ::sim_real_msg_interface::Commands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sim_real_msg_interface::Commands_<ContainerAllocator> const> ConstPtr;

}; // struct Commands_

typedef ::sim_real_msg_interface::Commands_<std::allocator<void> > Commands;

typedef boost::shared_ptr< ::sim_real_msg_interface::Commands > CommandsPtr;
typedef boost::shared_ptr< ::sim_real_msg_interface::Commands const> CommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sim_real_msg_interface::Commands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sim_real_msg_interface::Commands_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sim_real_msg_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sim_real_msg_interface': ['/home/huu201/workspace/gazebo_crrl_ugv/src/sim_real_msg_interface/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sim_real_msg_interface::Commands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sim_real_msg_interface::Commands_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sim_real_msg_interface::Commands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sim_real_msg_interface::Commands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_real_msg_interface::Commands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_real_msg_interface::Commands_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sim_real_msg_interface::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b37d025bd24f9e3a7356e8eb85f42da7";
  }

  static const char* value(const ::sim_real_msg_interface::Commands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb37d025bd24f9e3aULL;
  static const uint64_t static_value2 = 0x7356e8eb85f42da7ULL;
};

template<class ContainerAllocator>
struct DataType< ::sim_real_msg_interface::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sim_real_msg_interface/Commands";
  }

  static const char* value(const ::sim_real_msg_interface::Commands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sim_real_msg_interface::Commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float32 velocity\n\
float32 omega\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::sim_real_msg_interface::Commands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sim_real_msg_interface::Commands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity);
      stream.next(m.omega);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Commands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sim_real_msg_interface::Commands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sim_real_msg_interface::Commands_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "omega: ";
    Printer<float>::stream(s, indent + "  ", v.omega);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIM_REAL_MSG_INTERFACE_MESSAGE_COMMANDS_H
