# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sim_real_msg_interface/Odometry.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Odometry(genpy.Message):
  _md5sum = "89f83a34da9c89a443ae852ee70fa087"
  _type = "sim_real_msg_interface/Odometry"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
float32 ap_time
float32 wheel_R
float32 wheel_L
geometry_msgs/Vector3 gyro
geometry_msgs/Vector3 acc1
geometry_msgs/Vector3 acc2
geometry_msgs/Vector3 magn
float32 velocity
float32 omega
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','ap_time','wheel_R','wheel_L','gyro','acc1','acc2','magn','velocity','omega']
  _slot_types = ['std_msgs/Header','float32','float32','float32','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ap_time,wheel_R,wheel_L,gyro,acc1,acc2,magn,velocity,omega

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Odometry, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ap_time is None:
        self.ap_time = 0.
      if self.wheel_R is None:
        self.wheel_R = 0.
      if self.wheel_L is None:
        self.wheel_L = 0.
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Vector3()
      if self.acc1 is None:
        self.acc1 = geometry_msgs.msg.Vector3()
      if self.acc2 is None:
        self.acc2 = geometry_msgs.msg.Vector3()
      if self.magn is None:
        self.magn = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = 0.
      if self.omega is None:
        self.omega = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.ap_time = 0.
      self.wheel_R = 0.
      self.wheel_L = 0.
      self.gyro = geometry_msgs.msg.Vector3()
      self.acc1 = geometry_msgs.msg.Vector3()
      self.acc2 = geometry_msgs.msg.Vector3()
      self.magn = geometry_msgs.msg.Vector3()
      self.velocity = 0.
      self.omega = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f12d2f().pack(_x.ap_time, _x.wheel_R, _x.wheel_L, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.acc1.x, _x.acc1.y, _x.acc1.z, _x.acc2.x, _x.acc2.y, _x.acc2.z, _x.magn.x, _x.magn.y, _x.magn.z, _x.velocity, _x.omega))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Vector3()
      if self.acc1 is None:
        self.acc1 = geometry_msgs.msg.Vector3()
      if self.acc2 is None:
        self.acc2 = geometry_msgs.msg.Vector3()
      if self.magn is None:
        self.magn = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 116
      (_x.ap_time, _x.wheel_R, _x.wheel_L, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.acc1.x, _x.acc1.y, _x.acc1.z, _x.acc2.x, _x.acc2.y, _x.acc2.z, _x.magn.x, _x.magn.y, _x.magn.z, _x.velocity, _x.omega,) = _get_struct_3f12d2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f12d2f().pack(_x.ap_time, _x.wheel_R, _x.wheel_L, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.acc1.x, _x.acc1.y, _x.acc1.z, _x.acc2.x, _x.acc2.y, _x.acc2.z, _x.magn.x, _x.magn.y, _x.magn.z, _x.velocity, _x.omega))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Vector3()
      if self.acc1 is None:
        self.acc1 = geometry_msgs.msg.Vector3()
      if self.acc2 is None:
        self.acc2 = geometry_msgs.msg.Vector3()
      if self.magn is None:
        self.magn = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 116
      (_x.ap_time, _x.wheel_R, _x.wheel_L, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.acc1.x, _x.acc1.y, _x.acc1.z, _x.acc2.x, _x.acc2.y, _x.acc2.z, _x.magn.x, _x.magn.y, _x.magn.z, _x.velocity, _x.omega,) = _get_struct_3f12d2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f12d2f = None
def _get_struct_3f12d2f():
    global _struct_3f12d2f
    if _struct_3f12d2f is None:
        _struct_3f12d2f = struct.Struct("<3f12d2f")
    return _struct_3f12d2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
